# Generated by Django 4.2.30 on 2026-04-22 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good')], default='Good', max_length=20)),
                ('pickup_location', models.CharField(max_length=120)),
                ('seller_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_position', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='marketplace.category')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
